from crm.models.departments_model import Department
from crm.models.users_model import User
from crm.models.users_has_clients_model import UserHasClient
from crm.models.users_has_events_model import UserHasEvent
from crm.models.clients_model import Client
from crm.models.contracts_model import Contract
from crm.models.contract_status_model import ContractStatus
from crm.models.invoices_model import Invoice
from crm.models.events_model import Event
from crm.models.clients_model import Client
from crm.models.companies_model import Company
